### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by willdaly** [exactlyaaron/farm-manager#1]
copyright says eliza

**Comment by exactlyaaron** [comment]
Ha. Thanks for the heads up.

On Tue, Sep 16, 2014 at 5:05 PM, willdaly notifications@github.com wrote:

> copyright says eliza
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/exactlyaaron/farm-manager/issues/1.

## 

_Aaron Johnson_
_THINK. DESIGN. CREATE._

931-308-4091
www.aaronjohnsondesign.com
LinkedIn http://www.linkedin.com/pub/aaron-johnson/25/237/b30/
Youtube Channel http://www.youtube.com/johnson13design
